### ISSUE TITLE
Implement builder inner classes

### ISSUE THREAD

**Issue by cmungall** [phenopackets/phenopacket-reference-implementation#7]
Builder inner classes have been added for some POJOs, but these are not complete, and some work will need to be done to make them work with inheritance, see:

http://stackoverflow.com/questions/17164375/subclassing-a-java-builder-class

**Comment by cmungall** [comment]
@ julesjacobsen recommends that once we have builders we should make the objects immutable, declare fields final, and remove setters.

**Comment by cmungall** [comment]
We should first fully test the builder classes in the context of using jackson to map json to objects, seem to be some issues with constructors, see PhenotypeAssociationTest.testFromFile

http://stackoverflow.com/questions/7625783/jsonmappingexception-no-suitable-constructor-found-for-type-simple-type-class

**Comment by julesjacobsen** [comment]
This is an issue caused by using Builders. Jackson can do it, but it requires a few extra annotations - see commit 88b4a1be419d50e7e352fbe60c75b49a5dfdd2bd

**Comment by cmungall** [comment]
Hmm, it's starting to look a little more complex.

Let's look at the tradeoffs. Immutability of objects is a nice property, but we don't even have it with lists at the moment (unless we change the getters to always return copies). I can also see us needing to implement the Change pattern to make changes, and inflating the codebase with shadows of the object model...

@hdietze @jnguyenx @balhoff  what do you think?

**Comment by julesjacobsen** [comment]
Given the multiple levels of inheritance, I’m now not so convinced the builder idea is a good one either. We can still produce immutable lists using Collections.immutableList in the build() method, so this isn’t a show-stopper. Could there be a better way of representing these things without resorting to multiple levels of inheritance so that ClassInstance isn’t a second kind of Object? Maybe using a Java annotation like @LogicalInstance for ClassInstance and @LogicalClass for OntologyClass (not sure quite how that would work). Interfaces? Composition? Either way I think there will be a lot more code than we have now. We could just stick with what we have and the Bean pattern - maybe I'm overthinking it.

**Comment by julesjacobsen** [comment]
Outcome - Nope, let's not. 

Stick to simple POJO bean-pattern. It works way better with multiple levels of inheritance.
